### PR TITLE
Fixed recording of erroneous metrics for driver and API requests

### LINKED ISSUE #129: Metrics capturing erroneous API and Driver invocations do not capture the error
**What happened**:
All methods in [helpers](https://github.com/gardener/machine-controller-manager-provider-azure/tree/master/pkg/azure/access/helpers) have the following first statement:
```go
defer instrument.RecordAzAPIMetric(err, <label-Name>, time.Now())
```
Unfortunately this will always have the error has nil even when using named returned types. The correct way to invoke this should be:
```go
defer func(currentTime time.Time) {
   instrument.RecordAzAPIMetric(err, <label-Name>, currentTime)
}(time.Now)
```
This will ensure that if there is an error captured in the method then it will be made available to the deferred function.

**What you expected to happen**:
If there is an error in the API call then it should have been captured as a error metrics.

### PR DESCRIPTION
**Pull request by unmarshall**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #129 

**Special notes for your reviewer**:

**Release note**:

```improvement user
Fixed recording of erroneous metrics for driver and API requests
```

### CODE REVIEW

File: pkg/azure/access/helpers/disk.go [hunk 1]
```diff
@@ -32,7 +32,9 @@ const (
 // DeleteDisk deletes disk for passed in resourceGroup and diskName.
 // NOTE: All calls to this Azure API are instrumented as prometheus metric.
 func DeleteDisk(ctx context.Context, client *armcompute.DisksClient, resourceGroup, diskName string) (err error) {
-	defer instrument.RecordAzAPIMetric(err, diskDeleteServiceLabel, time.Now())
+	defer func(invocationTime time.Time) {
+		instrument.RecordAzAPIMetric(err, diskDeleteServiceLabel, invocationTime)
+	}(time.Now())
```
Comment (elankath) [inline pkg/azure/access/helpers/disk.go:37]: Why now just create a utility function to assist here instead of repeating lambda dozens of times ?

```go
func APIMetricRecorder(err error, azServiceName string) func() {
 invocationTime := time.Now()
 return func() {
  instrument.RecordAzAPIMetric(err, diskDeleteServiceLabel, invocationTime)
 }
}
```

```go
defer MeasureTime(err, diskDeleteServiceLabel)
```

Comment (unmarshall) [reply pkg/azure/access/helpers/disk.go:37]: ok thanks, will do that.

Comment (unmarshall) [reply pkg/azure/access/helpers/disk.go]: PTAL. Changes are done for both API and Driver metrics

Comment (rishabh-11) [reply pkg/azure/access/helpers/disk.go]: This won't work. The error will still be nil because it is a parameter to the function and hence calculated before the execution and not at the instance the defer is executed.

Comment (elankath) [reply pkg/azure/access/helpers/disk.go]: Yikes, this is right.🙈 `err` is a interface pointer in Golang which is treated as fat pointer copied by value, not reference, so the value will be `nil` at the end of the function even if was set midway. 
 
One needs to use a pointer to pointer approach here, sorry! (hitting my head). (Also, quickly tested this with/without error)

```go
func APIMetricRecorderFn(azServiceName string, errPtr *error) func() {
	invocationTime := time.Now()
	return func() {
		RecordAzAPIMetric(*errPtr, azServiceName, invocationTime)
	}
}
```

```go

func hailGod() error {
	var err error
	defer APIMetricRecorderFn("hailgod", &err)()
	fmt.Println("God Service Called")
	err = errors.New("noreply")
	return err
}

```
God Service Called
RecordAzAPIMetric: err: noreply, operation:hailgod, invocationTime: 2024-02-14 22:32:39.303707 +0530 IST m=+0.000132209

```

**Review by elankath — CHANGES_REQUESTED** [review]
sorry for dumb mistake, need `errPtr` and `&err` to be passed to recorder fn and not just `err`

File: pkg/azure/access/helpers/disk.go (hunk 1 above)
Comment (unmarshall) [reply pkg/azure/access/helpers/disk.go]: good catch. Thanks. Using pointer to a pointer is not used very often in golang code. There are reasons for that but in this there does not seem to be side effect therefore i have made the proposed change.

File: pkg/azure/access/helpers/disk.go [hunk 2]
```diff
@@ -32,7 +31,7 @@ const (
 // DeleteDisk deletes disk for passed in resourceGroup and diskName.
 // NOTE: All calls to this Azure API are instrumented as prometheus metric.
 func DeleteDisk(ctx context.Context, client *armcompute.DisksClient, resourceGroup, diskName string) (err error) {
-	defer instrument.RecordAzAPIMetric(err, diskDeleteServiceLabel, time.Now())
+	defer instrument.APIMetricRecorderFn(diskDeleteServiceLabel, &err)
```
Comment (rishabh-11) [inline pkg/azure/access/helpers/disk.go:34]:
```suggestion
	defer instrument.APIMetricRecorderFn(diskDeleteServiceLabel, &err)()
```

We need to execute the returned function to record the metric. Same change at other places as well

**Review by rishabh-11 — CHANGES_REQUESTED** [review]
Some minor changes needed. I'll test it once they are done.

File: pkg/azure/access/helpers/disk.go (hunk 2 above)
Comment (unmarshall) [reply pkg/azure/access/helpers/disk.go]: Thanks for pointing this out, changes are made and unit tests are now added which were missing before. PTAL

File: pkg/azure/access/helpers/disk.go [hunk 3]
```diff
@@ -32,7 +31,7 @@ const (
 // DeleteDisk deletes disk for passed in resourceGroup and diskName.
 // NOTE: All calls to this Azure API are instrumented as prometheus metric.
 func DeleteDisk(ctx context.Context, client *armcompute.DisksClient, resourceGroup, diskName string) (err error) {
-	defer instrument.RecordAzAPIMetric(err, diskDeleteServiceLabel, time.Now())
+	defer instrument.AZAPIMetricRecorderFn(diskDeleteServiceLabel, &err)()
```
Comment (rishabh-11) [inline pkg/azure/access/helpers/disk.go:34]: I think you need to pass the time here and not initialize it in the function.

File: pkg/azure/instrument/instrument_test.go [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+	reg := prometheus.NewRegistry()
+	g.Expect(reg.Register(metrics.APIRequestCount)).To(Succeed())
+	g.Expect(reg.Register(metrics.APIFailedRequestCount)).To(Succeed())
+	for _, tc := range testCases {
+		t.Run(tc.name, func(t *testing.T) {
+			defer metrics.APIRequestCount.Reset()
+			defer metrics.APIFailedRequestCount.Reset()
+			_ = deferredMetricsRecorderInvoker(tc.err != nil, false, AZAPIMetricRecorderFn)
+			if tc.err != nil {
+				g.Expect(testutil.CollectAndCount(metrics.APIFailedRequestCount)).To(Equal(1))
```
Comment (rishabh-11) [inline pkg/azure/instrument/instrument_test.go:42]:
```suggestion
				g.Expect(testutil.CollectAndCount(metrics.APIRequestCount)).To(Equal(0))
				g.Expect(testutil.CollectAndCount(metrics.APIFailedRequestCount)).To(Equal(1))
```

File: pkg/azure/instrument/instrument_test.go [hunk 5]
```diff
@@ -0,0 +1,111 @@
...
+				g.Expect(testutil.ToFloat64(metrics.APIFailedRequestCount.WithLabelValues(prometheusProviderLabelValue, serviceName))).To(Equal(float64(1)))
+			} else {
+				g.Expect(testutil.CollectAndCount(metrics.APIRequestCount)).To(Equal(1))
```
Comment (rishabh-11) [inline pkg/azure/instrument/instrument_test.go:45]:
```suggestion
				g.Expect(testutil.CollectAndCount(metrics.APIFailedRequestCount)).To(Equal(0))
				g.Expect(testutil.CollectAndCount(metrics.APIRequestCount)).To(Equal(1))

```

**Review by rishabh-11 — CHANGES_REQUESTED** [review]
small changes needed

File: pkg/azure/access/helpers/disk.go (hunk 3 above)
Comment (unmarshall) [reply pkg/azure/access/helpers/disk.go:34]: Not required as discussed, function value and parameters are evaluated eagerly.
https://go.dev/ref/spec#Defer_statements

File: pkg/azure/instrument/instrument.go [hunk 6]
```diff
@@ -50,6 +52,7 @@ func RecordAzAPIMetric(err error, azServiceName string, invocationTime time.Time
 
 	// compute the time taken to complete the AZ service call and record it as a metric
 	elapsed := time.Since(invocationTime)
+	fmt.Printf("Elapsed time: %v\n", elapsed)
```
Comment (rishabh-11) [inline pkg/azure/instrument/instrument.go:55]:
```suggestion
```
We can remove this imo

**Review by rishabh-11 — CHANGES_REQUESTED** [review]
looks good. just a small change needed

File: pkg/azure/instrument/instrument.go (hunk 6 above)
Comment (unmarshall) [reply pkg/azure/instrument/instrument.go]: ah this was left, removed and pushed the changes.

**Review by rishabh-11 — APPROVED** [review]
/lgtm

**Review by elankath — APPROVED** [review]
thanks for the fixes.
