### PR TITLE
Abort `ListMachines` call if resource group is gone.

### LINKED ISSUE #19: machine-controller-manager cannot delete Machine when the resource group is already deleted
**What happened**:

```
$ k -n shoot--foo--bar get machines shoot--foo--bar-bar-z3-5bf676f44d-kt27p -o yaml
```

```yaml
status:
  currentStatus:
    lastUpdateTime: "2020-11-20T07:52:09Z"
    phase: Terminating
  lastOperation:
    description: 'Cloud provider message - compute.VirtualMachinesClient#List: Failure
      responding to request: StatusCode=404 -- Original Error: autorest/azure: Service
      returned an error. Status=404 Code="ResourceGroupNotFound" Message="Resource
      group ''shoot--foo--bar'' could not be found."'
    lastUpdateTime: "2020-11-20T07:52:09Z"
    state: Failed
    type: Delete
```

**What you expected to happen**:
machine-controller-manager should be able to delete Machine when the resource group is already deleted. For example the azure cloud-controller-manager can handle this case and can delete Service of type LoadBalancer when the underlying resource-group is already deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an Azure Machine
2. Delete the underlying resource group
3. Ensure that machine-controller-manager cannot delete the Machine CR

**Anything else we need to know**:

**Environment**:
- machine-controller-manager version: v0.34.3

### PR DESCRIPTION
**Pull request by dkistner**
**What this PR does / why we need it**:
The deletion of a machine will be blocked in case the underlying resource group is not available on Azure.
The `DeleteMachine()` function is already checking if the resource group is available and if not the deletion flow will be aborted.
During the deletion flow the `ListMachines()` function is also called by other means e.g. safety controller and the list machine call towards Azure will fail if the resource group is gone. As result mcm-provider-azure is not able to complete the machine deletion.

This PR adds the resource group availability check also to the `ListMachines()` function in addition to the `DeleteMachine()` function.

**Which issue(s) this PR fixes**:
Fixes #19

**Special notes for your reviewer**:

**Release note**:

```improvement operator
An issue that let the safety controller block the machine deletion if the Azure resource group is not available has been fixed.
```

/invite @himanshu-kun

### CODE REVIEW

File: pkg/azure/utils.go [hunk 1]
```diff
@@ -1133,3 +1133,18 @@ func verifyAzureTags(tags map[string]*string, clusterNameTag, nodeRoleTag string
...
+
+// inspectResourceGroup inspects if a given resource group by name is available on Azure.
+// The function will return an error which will be nil if the resource group exists.
+// In case the resource group does not exists on Azure an NotFound error will be returned.
+// If the Azure api call not succeed for other reasons an Internal error will be returned.
+func inspectResourceGroup(ctx context.Context, clients spi.AzureDriverClientsInterface, resourceGroupName string) error {
+	if _, err := clients.GetGroup().Get(ctx, resourceGroupName); err != nil {
+		if NotFound(err) {
+			return status.Error(codes.NotFound, err.Error())
+		}
```
Comment (kon-angelo) [inline pkg/azure/utils.go:1145]: If these are MCM codes then the `NotFound` error code is not appropriate for `ListMachine` [ref](https://github.com/gardener/machine-controller-manager/blob/master/docs/development/machine_error_codes.md#listmachines-errors)

Because of that I am not in favor of setting external MCM error codes in utility funcs.

Comment (dkistner) [reply pkg/azure/utils.go:1145]: Thanks for this. What would you suggest in this case? Simply sending an ok?

Comment (kon-angelo) [reply pkg/azure/utils.go:1145]: @himanshu-kun can probably have a more informed opinion about the best reply.

Technically, no RG means that the list of machines is empty, so an ok should be fine. However, as it is right now it will mess with the DeleteMachine response replying with OK instead of NotFound (although an OK and NotFound for DeleteMachine are equivalent).

I would change `inspectResourceGroup` to 

```
resourceGroupExists(...) (bool, error)
```
That way you can discern if RG exists and then you can in ListMachines you can reply with an Ok and empty machine list and for Delete with NotFound

Comment (himanshu-kun) [reply pkg/azure/utils.go:1145]: yes I agree with @kon-angelo . His proposal looks good to me.

Comment (dkistner) [reply pkg/azure/utils.go]: I adressed the feedback, but I didn't go with a dedicated function to determine the rg availability.
As we need to handle the situation differently in `DeleteMachine()` and `ListMachines()` it doesn't bring too much benefit and it's not much dry.

In `ListMachines()` I simply return now an empty list of machine so that deletion can be completed. As we have no proper error code for this situation I added a log message for this case.

PTAL :)

**Review by kon-angelo — APPROVED** [review]
/lgtm
