### PR TITLE
Orphan Safety Controller missing VM's due to large resource query

### LINKED ISSUE #202: Orphan Safety Controller missing VM's due to large resource query
**What happened**:

The orphan safety controller in MCM that is responsible for cleaning up orphaned VM's i.e., VM instances that are not associated with `Machine` objects is missing several instances in its cleanup logic for large clusters (>1000 resources). It may take a very long time before full cleanup occurs.

**What you expected to happen**:

orphan safety controller should effectively cleanup ALL orphaned VM instances and their resources at its configured `machine-safety-orphan-vms-period` without leaving instances or their resources behind for large clusters.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a Azure shoot cluster with a worker pool beyond 1000 with some disks and NIC's.
- Decreate the `machine-safety-orphan-vms-period` to a lower value for ease of reproduction
- Force delete many `Machine` objects (after removing `finalizer`) using `kubectl`
- There is high chance that orphan controller will not be able to remove all orphaned VM instances corresponding to delete `Machine` objects.

**Anything else we need to know**:

* This is likely happening due to bad pagination handling in the Azure Resource Graph response. Situation only occurs when resource count > 1000, which is the default page size for resource graph requests. Issue will be updated with further details of fix later.

**Environment**:
- Azure Cloud

### PR DESCRIPTION
**Pull request by gagan16k**
**What this PR does / why we need it**
This pull request adds pagination logic in the `QueryAndMap` function within `pkg/azure/access/helpers/resourcegraph.go`, ensuring all results are retrieved from the Azure Resource Graph API instead of just the first page.

**Which issue(s) this PR  #fixes**:
Fixes #202

Enhancements to pagination and result handling:
* Modified the query execution loop to repeatedly fetch results using the [`skipToken`](https://learn.microsoft.com/en-us/rest/api/azureresourcegraph/resourcegraph/resources/resources?view=rest-azureresourcegraph-resourcegraph-2022-10-01&tabs=HTTP#next-page-query), handling paginated responses from the Resource Graph API until all pages are processed.
* Updated the function to accumulate results across all pages and return the complete set, rather than returning after the first page.

**Special notes for your reviewer**:
Passed unit and integration tests
**Release note**:

```bugfix operator
Fixed an issue in the orphan safety controller where orphaned VM instances were not fully cleaned up in large Azure clusters due to missing pagination in Azure Resource Graph queries.
```

### CODE REVIEW

**Comment by gagan16k** [comment]
Attaching unit test and IT logs

## Integration Tests
<details>
<summary>Updated IT test logs</summary>
Random Seed: 1760470603

Will run 10 of 10 specs
------------------------------
[BeforeSuite]
/Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/test/integration/controller/controller_test.go:47
  > Enter [BeforeSuite] TOP-LEVEL @ 10/15/25 01:06:50.302
  STEP: Checking for the clusters if provided are available @ 10/15/25 01:06:50.303
  2025/10/15 01:06:50 Control cluster kube-config - /Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/dev/kube-configs/kubeconfig_control.yaml
  2025/10/15 01:06:50 Target cluster kube-config  - /Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/dev/kube-configs/kubeconfig_target.yaml
  STEP: Killing any existing processes @ 10/15/25 01:06:53.053
  STEP: Checking Machine-Controller-Manager repo is available at: ../../../dev/mcm @ 10/15/25 01:06:53.299
  STEP: Scaledown existing machine controllers @ 10/15/25 01:06:53.3
  STEP: Starting Machine Controller  @ 10/15/25 01:06:53.473
  STEP: Starting Machine Controller Manager @ 10/15/25 01:06:53.48
  STEP: Cleaning any old resources @ 10/15/25 01:06:53.483
  2025/10/15 01:06:53 machinedeployments.machine.sapcloud.io "test-machine-deployment" not found
  2025/10/15 01:06:53 machines.machine.sapcloud.io "test-machine" not found
  2025/10/15 01:06:53 machineclasses.machine.sapcloud.io "test-mc-v1" not found
  2025/10/15 01:06:54 machineclasses.machine.sapcloud.io "test-mc-v2" not found
  STEP: Setup MachineClass @ 10/15/25 01:06:54.135
  STEP: Looking for machineclass resource in the control cluster @ 10/15/25 01:06:55.298
  STEP: Looking for secrets refered in machineclass in the control cluster @ 10/15/25 01:06:55.462
  STEP: Initializing orphan resource tracker @ 10/15/25 01:06:55.781
I1015 01:07:04.484210   32239 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 0
  2025/10/15 01:07:07 orphan resource tracker initialized
  < Exit [BeforeSuite] TOP-LEVEL @ 10/15/25 01:07:07.401 (17.099s)
[BeforeSuite] PASSED [17.099 seconds]
------------------------------
Machine controllers test machine resource creation should not lead to any errors and add 1 more node in target cluster
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:649
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:07:07.401
  STEP: Checking machineController process is running @ 10/15/25 01:07:07.402
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:07:07.402
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:07:07.402
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:07:08.229 (827ms)
  > Enter [It] should not lead to any errors and add 1 more node in target cluster @ 10/15/25 01:07:08.229
  STEP: Checking for errors @ 10/15/25 01:07:08.439
  STEP: Waiting until number of ready nodes is 1 more than initial nodes @ 10/15/25 01:07:08.599
  < Exit [It] should not lead to any errors and add 1 more node in target cluster @ 10/15/25 01:10:35.478 (3m27.249s)
• [208.077 seconds]
------------------------------
Machine controllers test machine resource deletion when machines available should not lead to errors and remove 1 node in target cluster
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:678
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:10:35.48
  STEP: Checking machineController process is running @ 10/15/25 01:10:35.481
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:10:35.481
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:10:35.481
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:10:35.908 (428ms)
  > Enter [It] should not lead to errors and remove 1 node in target cluster @ 10/15/25 01:10:35.909
  STEP: Checking for errors @ 10/15/25 01:10:36.984
  STEP: Waiting until test-machine machine object is deleted @ 10/15/25 01:10:37.148
  STEP: Waiting until number of ready nodes is equal to number of initial nodes @ 10/15/25 01:11:29.208
  < Exit [It] should not lead to errors and remove 1 node in target cluster @ 10/15/25 01:11:30.036 (54.127s)
• [54.555 seconds]
------------------------------
Machine controllers test machine resource deletion when machines are not available should keep nodes intact
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:717
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:11:30.036
  STEP: Checking machineController process is running @ 10/15/25 01:11:30.036
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:11:30.036
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:11:30.036
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:11:30.46 (424ms)
  > Enter [It] should keep nodes intact @ 10/15/25 01:11:30.46
  STEP: Skipping as there are machines available and this check can't be performed @ 10/15/25 01:11:30.782
  < Exit [It] should keep nodes intact @ 10/15/25 01:11:30.782 (321ms)
• [0.746 seconds]
------------------------------
Machine controllers test machine deployment resource creation with replicas=0, scale up with replicas=1 should not lead to errors and add 1 more node to target cluster
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:745
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:11:30.782
  STEP: Checking machineController process is running @ 10/15/25 01:11:30.782
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:11:30.782
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:11:30.782
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:11:31.213 (431ms)
  > Enter [It] should not lead to errors and add 1 more node to target cluster @ 10/15/25 01:11:31.213
  STEP: Checking for errors @ 10/15/25 01:11:31.426
  STEP: Waiting for Machine Set to be created @ 10/15/25 01:11:31.591
  STEP: Updating machineDeployment replicas to 1 @ 10/15/25 01:11:34.241
  STEP: Checking if machineDeployment's status has been updated with correct conditions @ 10/15/25 01:11:34.57
  STEP: Checking number of ready nodes==1 @ 10/15/25 01:15:54.474
  STEP: Fetching initial number of machineset freeze events @ 10/15/25 01:15:55.901
  < Exit [It] should not lead to errors and add 1 more node to target cluster @ 10/15/25 01:15:56.547 (4m25.357s)
• [265.788 seconds]
------------------------------
Machine controllers test machine deployment resource scale-up with replicas=6 should not lead to errors and add further 5 nodes to target cluster
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:813
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:15:56.547
  STEP: Checking machineController process is running @ 10/15/25 01:15:56.547
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:15:56.547
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:15:56.547
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:15:56.974 (427ms)
  > Enter [It] should not lead to errors and add further 5 nodes to target cluster @ 10/15/25 01:15:56.975
  STEP: Checking for errors @ 10/15/25 01:15:57.315
  STEP: Checking number of ready nodes are 6 more than initial @ 10/15/25 01:15:57.315
  ------------------------------
  Automatically polling progress:
    Machine controllers test machine deployment resource scale-up with replicas=6 should not lead to errors and add further 5 nodes to target cluster (Spec Runtime: 5m0.429s)
      /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:813
      In [It] (Node Runtime: 5m0.001s)
        /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:813
        At [By Step] Checking number of ready nodes are 6 more than initial (Step Runtime: 4m59.661s)
          /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:828

        Spec Goroutine
        goroutine 517 [select]
          github.com/onsi/gomega/internal.(*AsyncAssertion).match(0x14000062070, {0x1041f0430, 0x140000ffb60}, 0x1, {0x0, 0x0, 0x0})
            /Users/I765230/go/pkg/mod/github.com/onsi/gomega@v1.36.2/internal/async_assertion.go:546
          github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0x14000062070, {0x1041f0430, 0x140000ffb60}, {0x0, 0x0, 0x0})
            /Users/I765230/go/pkg/mod/github.com/onsi/gomega@v1.36.2/internal/async_assertion.go:145
        > github.com/gardener/machine-controller-manager/pkg/test/integration/common.(*IntegrationTestFramework).ControllerTests.func2.2.1()
            /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:838
              | 		c.timeout,
              | 		c.pollingInterval).
              > 		Should(gomega.BeNumerically("==", initialNodes+6))
              | })
              |
          github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x140004bf200?, 0x0?})
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/node.go:475
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/suite.go:894
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 68
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/suite.go:881
  ------------------------------
  < Exit [It] should not lead to errors and add further 5 nodes to target cluster @ 10/15/25 01:21:44.118 (5m47.144s)
• [347.571 seconds]
------------------------------
Machine controllers test machine deployment resource scale-down with replicas=2 should not lead to errors and remove 4 nodes from target cluster
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:843
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:21:44.118
  STEP: Checking machineController process is running @ 10/15/25 01:21:44.118
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:21:44.118
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:21:44.118
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:21:44.745 (627ms)
  > Enter [It] should not lead to errors and remove 4 nodes from target cluster @ 10/15/25 01:21:44.745
  STEP: Checking for errors @ 10/15/25 01:21:45.84
  STEP: Checking number of ready nodes are 2 more than initial @ 10/15/25 01:21:45.84
  < Exit [It] should not lead to errors and remove 4 nodes from target cluster @ 10/15/25 01:22:39.859 (55.114s)
• [55.741 seconds]
------------------------------
Machine controllers test machine deployment resource scale-down with replicas=2 should freeze and unfreeze machineset temporarily
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:872
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:22:39.859
  STEP: Checking machineController process is running @ 10/15/25 01:22:39.859
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:22:39.859
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:22:39.859
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:22:40.342 (483ms)
  > Enter [It] should freeze and unfreeze machineset temporarily @ 10/15/25 01:22:40.342
  < Exit [It] should freeze and unfreeze machineset temporarily @ 10/15/25 01:22:40.995 (653ms)
• [1.136 seconds]
------------------------------
Machine controllers test machine deployment resource updation to v2 machine-class and replicas=4 should upgrade machines and add more nodes to target
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:881
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:22:40.995
  STEP: Checking machineController process is running @ 10/15/25 01:22:40.996
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:22:40.996
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:22:40.996
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:22:41.612 (616ms)
  > Enter [It] should upgrade machines and add more nodes to target @ 10/15/25 01:22:41.612
  STEP: Checking for errors @ 10/15/25 01:22:41.935
  STEP: UpdatedReplicas to be 4 @ 10/15/25 01:22:41.935
  STEP: AvailableReplicas to be 4 @ 10/15/25 01:22:48.565
  STEP: Number of ready nodes be 4 more @ 10/15/25 01:27:25.373
  ------------------------------
  Automatically polling progress:
    Machine controllers test machine deployment resource updation to v2 machine-class and replicas=4 should upgrade machines and add more nodes to target (Spec Runtime: 5m0.617s)
      /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:881
      In [It] (Node Runtime: 5m0s)
        /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:881
        At [By Step] Number of ready nodes be 4 more (Step Runtime: 16.239s)
          /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:919

        Spec Goroutine
        goroutine 695 [select]
          github.com/onsi/gomega/internal.(*AsyncAssertion).match(0x14000063500, {0x1041f0430, 0x140008c6510}, 0x1, {0x0, 0x0, 0x0})
            /Users/I765230/go/pkg/mod/github.com/onsi/gomega@v1.36.2/internal/async_assertion.go:546
          github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0x14000063500, {0x1041f0430, 0x140008c6510}, {0x0, 0x0, 0x0})
            /Users/I765230/go/pkg/mod/github.com/onsi/gomega@v1.36.2/internal/async_assertion.go:145
        > github.com/gardener/machine-controller-manager/pkg/test/integration/common.(*IntegrationTestFramework).ControllerTests.func2.4.1()
            /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:924
              | 	c.timeout,
              | 	c.pollingInterval).
              > 	Should(gomega.BeNumerically("==", initialNodes+4))
              | gomega.Eventually(
              | 	c.TargetCluster.GetNumberOfReadyNodes,
          github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x140004bf680?, 0x140002b5540?})
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/node.go:475
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/suite.go:894
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 68
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/suite.go:881
  ------------------------------
  Automatically polling progress:
    Machine controllers test machine deployment resource updation to v2 machine-class and replicas=4 should upgrade machines and add more nodes to target (Spec Runtime: 6m0.621s)
      /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:881
      In [It] (Node Runtime: 6m0.004s)
        /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:881
        At [By Step] Number of ready nodes be 4 more (Step Runtime: 1m16.243s)
          /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:919

        Spec Goroutine
        goroutine 695 [select]
          github.com/onsi/gomega/internal.(*AsyncAssertion).match(0x14000063500, {0x1041f0430, 0x140008c6510}, 0x1, {0x0, 0x0, 0x0})
            /Users/I765230/go/pkg/mod/github.com/onsi/gomega@v1.36.2/internal/async_assertion.go:546
          github.com/onsi/gomega/internal.(*AsyncAssertion).Should(0x14000063500, {0x1041f0430, 0x140008c6510}, {0x0, 0x0, 0x0})
            /Users/I765230/go/pkg/mod/github.com/onsi/gomega@v1.36.2/internal/async_assertion.go:145
        > github.com/gardener/machine-controller-manager/pkg/test/integration/common.(*IntegrationTestFramework).ControllerTests.func2.4.1()
            /Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:924
              | 	c.timeout,
              | 	c.pollingInterval).
              > 	Should(gomega.BeNumerically("==", initialNodes+4))
              | gomega.Eventually(
              | 	c.TargetCluster.GetNumberOfReadyNodes,
          github.com/onsi/ginkgo/v2/internal.extractBodyFunction.func3({0x140004bf680?, 0x140002b5540?})
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/node.go:475
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode.func3()
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/suite.go:894
          github.com/onsi/ginkgo/v2/internal.(*Suite).runNode in goroutine 68
            /Users/I765230/go/pkg/mod/github.com/onsi/ginkgo/v2@v2.23.0/internal/suite.go:881
  ------------------------------
  < Exit [It] should upgrade machines and add more nodes to target @ 10/15/25 01:29:36.524 (6m54.925s)
• [415.542 seconds]
------------------------------
Machine controllers test machine deployment resource deletion When there are machine deployment(s) available in control cluster should not lead to errors and list only initial nodes
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:935
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:29:36.524
  STEP: Checking machineController process is running @ 10/15/25 01:29:36.524
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:29:36.524
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:29:36.524
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:29:36.965 (441ms)
  > Enter [It] should not lead to errors and list only initial nodes @ 10/15/25 01:29:36.965
  STEP: Checking for errors @ 10/15/25 01:29:37.804
  STEP: Waiting until number of ready nodes is equal to number of initial  nodes @ 10/15/25 01:29:37.978
  < Exit [It] should not lead to errors and list only initial nodes @ 10/15/25 01:30:34.701 (57.736s)
• [58.178 seconds]
------------------------------
Machine controllers test orphaned resources when the hyperscaler resources are queried should have been deleted
/Users/I765230/go/pkg/mod/github.com/gardener/machine-controller-manager@v0.60.0/pkg/test/integration/common/framework.go:972
  > Enter [BeforeEach] Machine controllers test @ 10/15/25 01:30:34.702
  STEP: Checking machineController process is running @ 10/15/25 01:30:34.702
  STEP: Checking machineControllerManager process is running @ 10/15/25 01:30:34.702
  STEP: Checking nodes in target cluster are healthy @ 10/15/25 01:30:34.702
  < Exit [BeforeEach] Machine controllers test @ 10/15/25 01:30:35.125 (423ms)
  > Enter [It] should have been deleted @ 10/15/25 01:30:35.125
  STEP: Querying and comparing @ 10/15/25 01:30:35.125
I1015 01:30:42.300080   32239 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 0
  < Exit [It] should have been deleted @ 10/15/25 01:30:45.168 (10.043s)
• [10.466 seconds]
------------------------------
[AfterSuite]
/Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/test/integration/controller/controller_test.go:49
  > Enter [AfterSuite] TOP-LEVEL @ 10/15/25 01:30:45.168
  STEP: Running Cleanup @ 10/15/25 01:30:45.168
  2025/10/15 01:31:05 machinedeployments.machine.sapcloud.io "test-machine-deployment" not found
  2025/10/15 01:31:05 machines.machine.sapcloud.io "test-machine" not found
  2025/10/15 01:31:05 deleting test-mc-v1 machineclass
  2025/10/15 01:31:06 machineclass deleted
  2025/10/15 01:31:06 deleting test-mc-v2 machineclass
  2025/10/15 01:31:06 machineclass deleted
  STEP: Killing any existing processes @ 10/15/25 01:31:06.845
  2025/10/15 01:31:06 controller_manager --control-kubeconfig=/Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/dev/kube-configs/kubeconfig_control.yaml --target-kubeconfig=/Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/dev/kube-configs/kubeconfig_target.yaml --namespace=shoot--i765230--demo-az --safety-up=2 --safety-down=1 --machine-safety-overshooting-period=300ms --leader-elect=false --v=3
  2025/10/15 01:31:06 stopMCM killed MCM process(es) with pid(s): [32314]
  2025/10/15 01:31:07 main --control-kubeconfig=/Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/dev/kube-configs/kubeconfig_control.yaml --target-kubeconfig=/Users/I765230/go/src/github.com/gagan16k/machine-controller-manager-provider-azure/dev/kube-configs/kubeconfig_target.yaml --namespace=shoot--i765230--demo-az --machine-creation-timeout=20m --machine-drain-timeout=5m --machine-health-timeout=10m --machine-pv-detach-timeout=2m --machine-safety-apiserver-statuscheck-timeout=30s --machine-safety-apiserver-statuscheck-period=1m --machine-safety-orphan-vms-period=30m --v=3
  2025/10/15 01:31:07 stopMCM killed MCM process(es) with pid(s): [32319]
  STEP: Scale back the existing machine controllers @ 10/15/25 01:31:07.091
  < Exit [AfterSuite] TOP-LEVEL @ 10/15/25 01:31:07.71 (22.542s)
[AfterSuite] PASSED [22.542 seconds]
------------------------------

Ran 10 of 10 Specs in 1457.445 seconds
SUCCESS! -- 10 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS

Ginkgo ran 1 suite in 24m24.656266792s
Test Suite Passed
Integration tests completed successfully
</details>

## Unit test
Test file  `resourcegraph_test.go` contains fake implementation of ResourceGraphClient to apply different test cases on `QueryAndMap`

Run tests with `go test -v ./pkg/azure/access/helpers/...` command
<details>
<summary>Unit test logs</summary>
=== RUN   TestQueryAndMap_Success_SinglePage
I1015 02:30:56.389311   33735 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 3
--- PASS: TestQueryAndMap_Success_SinglePage (0.00s)
=== RUN   TestQueryAndMap_Success_MultiplePages
I1015 02:30:56.389778   33735 resourcegraph.go:88] Fetching next page (page 2) with skipToken: token-page2
I1015 02:30:56.389786   33735 resourcegraph.go:88] Fetching next page (page 3) with skipToken: token-page3
I1015 02:30:56.389795   33735 resourcegraph.go:92] Query completed: fetched 3 pages, total results: 5
--- PASS: TestQueryAndMap_Success_MultiplePages (0.00s)
=== RUN   TestQueryAndMap_NoResults
I1015 02:30:56.389828   33735 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 0
--- PASS: TestQueryAndMap_NoResults (0.00s)
=== RUN   TestQueryAndMap_APIError
E1015 02:30:56.389914   33735 errors.go:66] ResourceGraphQuery failure to execute Query: Resources | where type =~ 'microsoft.compute/virtualmachines', with skipToken: <nil>: API call failed: AuthorizationFailed
--- PASS: TestQueryAndMap_APIError (0.00s)
=== RUN   TestQueryAndMap_ErrorInMiddleOfPagination
I1015 02:30:56.389945   33735 resourcegraph.go:88] Fetching next page (page 2) with skipToken: token-page2
E1015 02:30:56.389951   33735 errors.go:66] ResourceGraphQuery failure to execute Query: Resources | where type =~ 'microsoft.compute/virtualmachines', with skipToken: token-page2: network error during pagination
--- PASS: TestQueryAndMap_ErrorInMiddleOfPagination (0.00s)
=== RUN   TestMapper_IncompleteData
=== RUN   TestMapper_IncompleteData/missing_name_field
=== RUN   TestMapper_IncompleteData/missing_id_field
=== RUN   TestMapper_IncompleteData/missing_location_field
=== RUN   TestMapper_IncompleteData/wrong_type_for_name
=== RUN   TestMapper_IncompleteData/all_fields_present_and_correct
--- PASS: TestMapper_IncompleteData (0.00s)
    --- PASS: TestMapper_IncompleteData/missing_name_field (0.00s)
    --- PASS: TestMapper_IncompleteData/missing_id_field (0.00s)
    --- PASS: TestMapper_IncompleteData/missing_location_field (0.00s)
    --- PASS: TestMapper_IncompleteData/wrong_type_for_name (0.00s)
    --- PASS: TestMapper_IncompleteData/all_fields_present_and_correct (0.00s)
=== RUN   TestEmptySkipToken
I1015 02:30:56.390109   33735 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 2
--- PASS: TestEmptySkipToken (0.00s)
=== RUN   TestQueryAndMap_WithMapperFiltering
I1015 02:30:56.390142   33735 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 0
--- PASS: TestQueryAndMap_WithMapperFiltering (0.00s)
=== RUN   TestQueryAndMap_WithQueryTemplateAndArgs
I1015 02:30:56.390188   33735 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 2
--- PASS: TestQueryAndMap_WithQueryTemplateAndArgs (0.00s)
=== RUN   TestFakeResourceGraphClient_Reset
I1015 02:30:56.390215   33735 resourcegraph.go:92] Query completed: fetched 1 pages, total results: 1
--- PASS: TestFakeResourceGraphClient_Reset (0.00s)
PASS
ok  	github.com/gardener/machine-controller-manager-provider-azure/pkg/azure/access/helpers	0.233s
</details>

File: pkg/azure/access/helpers/resourcegraph_test.go [hunk 1]
```diff
@@ -0,0 +1,354 @@
...
+
+func TestQueryAndMap_NoResults(t *testing.T) {
+	g := NewWithT(t)
+	ctx := context.Background()
+
+	fakeClient := NewFakeResourceGraphClient().
+		AddResponse(armresourcegraph.ClientResourcesResponse{
+			QueryResponse: armresourcegraph.QueryResponse{
+				TotalRecords: to.Ptr[int64](0),
+				Data:         []interface{}{},
```
Comment (takoverflow) [inline pkg/azure/access/helpers/resourcegraph_test.go]:
```suggestion
				Data:         nil,
```

File: pkg/azure/access/helpers/resourcegraph.go [hunk 2]
```diff
@@ -12,49 +12,83 @@ import (
...
 
-	// resourceResponse.Data is a []interface{}
-	if objSlice, ok := resources.Data.([]interface{}); ok {
-		for _, obj := range objSlice {
-			// Each obj in resourceResponse.Data is a map[string]Interface{}
-			rowElements := obj.(map[string]interface{})
-			result := mapperFn(rowElements)
-			if result != nil {
-				results = append(results, *result)
+		if resources.TotalRecords == pointer.Int64(0) {
```
Comment (takoverflow) [inline pkg/azure/access/helpers/resourcegraph.go]: It's not correct to compare the pointers to check if the values are same since the pointers would correspond to different addresses. Thus this condition would never be true.
