### PR TITLE
Map Azure error codes to `ResourceExhausted` error code

### LINKED ISSUE #187: SkuNotAvailable machine provisioning errors can lead to Machines stuck in Terminating
**What happened**:
The CA (`cluster-autoscaler`) scaled up a Node in the wrong NodeGroup which caused the following `SkuNotAvailable` error when provisoning the machine. This further lead to the Machine being stuck in `Terminating` phase when the MCM decide to delete the Machine. And the CA was unable to scale a node in a different NodeGroup as this Machine was stuck.

```
{
  "error": {
    "code": "SkuNotAvailable",
    "message": "The requested VM size for resource 'Following SKUs have failed for Capacity Restrictions: Standard_L64s_v3' is currently not available in location 'westus2'. Please try another size or deploy to a different location or different zone. See https://aka.ms/azureskunotavailable for details.",
    "target": "vmSize"
  }
}
```

**What you expected to happen**:

* `SkuNotAvailable` errors when provisioning Azure instances should be treated `ResourceExhausted` errors and not as internval errors as they are being done currently
*  Failure in provisioning Machines with above error code should not lead to Machine being stuck.

**How to reproduce it (as minimally and precisely as possible)**:

* Define a worker pool with an instance type not available in a zone.
* Define workload that will trigger scale up in this worker pool.

**Anything else we need to know**:

**Environment**:

### PR DESCRIPTION
**Pull request by aaronfern**
**What this PR does / why we need it**:
This PR maps the following errors returned by Azure during VM creation to the `ResourceExhausted` error code.
1. SkuNotAvailable
2. AllocationFailed
3. ResourceQuotaExceeded

**Which issue(s) this PR fixes**:
Fixes #187 

**Special notes for your reviewer**:

**Release note**:

```improvement operator
SkuNotAvailable error is now mapped to ResourceExhausted error code
```
```improvement operator
AllocationFailed error is now mapped to ResourceExhausted error code
```
```improvement operator
ResourceQuotaExceeded error is now mapped to ResourceExhausted error code
```

### CODE REVIEW

**Review by kon-angelo — APPROVED** [review]
/lgtm

File: pkg/azure/access/errors/errors.go [hunk 1]
```diff
@@ -19,6 +19,8 @@ import (
 const (
 	// ZonalAllocationFailedAzErrorCode is an Azure error code indicating that there is insufficient capacity in the target zone.
 	ZonalAllocationFailedAzErrorCode = "ZonalAllocationFailed"
+	// SkuNotAvailableErrorCode is an Azure error code that indicates the specific resource SKU (e.g., a virtual machine size) selected isn't currently available.
```
Comment (takoverflow) [inline pkg/azure/access/errors/errors.go:22]: Other relevant azure errors that can possibly be mapped to `ResourceExhausted` error codes ([Ref](https://learn.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/common-deployment-errors)):
- `AllocationFailed`
- `ResourceQuotaExceeded`

(Please check if any other errors are relevant)
