### PR TITLE
Deal with terminal state vm in deleteMachine

### LINKED ISSUE #115: Add support for force deleting VM when its provisioning state is FAILED
**What would you like to be added**:
In Azure if a Virtual Machine has `ProvisionState` set to `Failed` then it neither be updated or deleted. In this case the VM is stuck in this state. If one wishes to delete this VM then `ForceDelete` needs to be set to true  in `VirtualMachinesClientBeginDeleteOptions` when making a call to delete the VM.

**Why is this needed**:
So that the VM is not stuck in terminal state.
Canary issue #4358 is one such example.

### PR DESCRIPTION
**Pull request by himanshu-kun**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #115 

Refer canary ticket # 4426

**Special notes for your reviewer**:
Pending manual test, will merge post that.

**Release note**:

```bugfix operator
Disk detachment step is skipped while terminating terminal state vms. Terminal state vms have `provisioningState` as `Failed`
```

### CODE REVIEW

File: pkg/azure/utils.go [hunk 1]
```diff
@@ -595,12 +603,20 @@ func (d *MachinePlugin) createVMNicDisk(req *driver.CreateMachineRequest) (*comp
...
+		if !isVirtualMachineInTerminalState(vm) && !isVirtualMachineMarkedForDeletion(vm) {
+			klog.V(2).Infof("VM %s is neither in terminal state nor marked for deletion. Proceeding with disk detachments..", VMName)
+			if detachmentErr := waitForDataDiskDetachment(ctx, clients, resourceGroupName, vm); detachmentErr != nil {
+				return detachmentErr
+			}
+		}
+
+		if isVirtualMachineInTerminalState(vm) {
+			klog.V(2).Infof("VM %s is in terminal state.. Proceeding with deletion of VM", VMName)
 		}
```
Comment (rishabh-11) [inline pkg/azure/utils.go:618]:
```suggestion
		if isVirtualMachineInTerminalState(vm) {
			klog.V(2).Infof("VM %s is in terminal state.. Proceeding with deletion of VM", VMName)
		} else if !isVirtualMachineMarkedForDeletion(vm) {
			klog.V(2).Infof("VM %s is neither in terminal state nor marked for deletion. Proceeding with disk detachments..", VMName)
			if detachmentErr := waitForDataDiskDetachment(ctx, clients, resourceGroupName, vm); detachmentErr != nil {
				return detachmentErr
			}
		}
```

**Review by rishabh-11 — CHANGES_REQUESTED** [review]
requesting a small change.

**Review by rishabh-11 — APPROVED** [review]
/lgtm
